---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  #namespace: echoserver
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - image: imageimpressario/echoserver:1.0.182
          name: echoserver
          ports:
            - containerPort: 8080
